all:
	gcc -o file main.c -lpthread #-std=c11 -_XOPEN_SOURCE
	gcc -o cfile mainc.c -lpthread #-std=c11 -_XOPEN_SOURCE
rm:
	rm -rf *.o file
cl:
	gcc -o cfile mainc.c -lpthread #-std=c11 -_XOPEN_SOURCE
se:
	gcc -o file main.c -lpthread #-std=c11 -_XOPEN_SOURCE
